### ISSUE TITLE
Lister les changements du ME

### ISSUE THREAD

**Issue by arnaudcordier** [edinum/nova#52]
Il faudrait une liste exhaustive des changements apportés au ME par rapport à celui de base d'OE.

Je ferais un script pour les appliquer sur les nouveaux sites.

Pas la peine d'être super précis, je prendrai les bonnes définition dans la base de données. Mais au moins assez d'info pour que je puisse retrouver les bons trucs

**Comment by brrd** [comment]
Fait dans https://github.com/edinum/lodel-options-extra
