### ISSUE TITLE
Problème de styles des listes 

### ISSUE THREAD

**Issue by brrd** [edinum/nova#65]
Dans l'enchaînement `ul > li > ol > li`, le dernier `li` apparaît avec une puce et non un chiffre. 

Cela vient de : 

https://github.com/edinum/nova/blob/761255e5d963f08cbaec4fa0573a174ff7f2a49f/less/site.less#L532

où il faut utiliser le sélecteur enfant `ol.texte > li`.

**Comment by ShazaamYo** [comment]
ok j'ai mis ul.texte > li à la place de ul.texte li et tout semble bien marcher sur le texte transmis
