### ISSUE TITLE
info rss a retirer

### ISSUE THREAD

**Issue by ShazaamYo** [edinum/nova#67]
Quand on est sur la page d’un flux (par exemple : https://publications-prairial.fr/arabesques/index.php?id=1505), chaque info se termine par « L’article XXX » est apparu en premier sur XXX ». il faut supprimer systématiquement cette information.

**Comment by brrd** [comment]
Ça vient pas de la nova mais des flux RSS de l'Abes. On ne va pas commencer à bricoler le texte des flux au cas par cas, sinon on s'en sortira jamais. Si vraiment c'est important de ne pas avoir cette information alors il faut demander à l'Abes de la retirer.
