### ISSUE TITLE
erreur doc github

### ISSUE THREAD

**Issue by ShazaamYo** [edinum/nova#68]
remarque d’Olivier :

J’ai noté une erreur, dans le passage suivant de la documentation de Github (branche Outils) pour l’installation des dépendances :

"Installer le dossier lodel-textfunc/ dans le même dossier que le dossier de l'installation pricipale de lodel, et ajouter dans lodelconfig.php :

include_once('../lodel-textfunc/textfunc_local.php') ;"

Le chemin donné n’est pas cohérent avec celui de search.php qui est appelé dans textfunc_local.php ( include_once('../lodel/scripts/searchfunc.php')).

D’autre part, comme le répertoire a été renommé lodel-common, ce serait plus clair de remplacer lodel-textfunc par lodel-common.

**Comment by arnaudcordier** [comment]
le chemin est bon, le working directory est le dossier du site lodel.
Il faut nommer le dossier lodel-textfunc tout comme le projet auquel il fait référence https://github.com/edinum/lodel-textfunc
