### ISSUE TITLE
Erreur dans l'ordre des metas author et DC.creator

### ISSUE THREAD

**Issue by SylDanh** [edinum/nova#90]
Bonjour,

Il y a une erreur dans l'ordre des meta author et DC.creator

dans le fichier macros_head.html

`<LOOP NAME="head_metadonnees_auteurs" TABLE="auteurs" WHERE="type='auteur'" WHERE="iddocument='[#ID]'" ORDER="rank">`
=>
`<LOOP NAME="head_metadonnees_auteurs" TABLE="auteurs" WHERE="type='auteur'" WHERE="iddocument='[#ID]'" ORDER="degree">`

et 
`<LOOP NAME="head_metadonnees_dc_creator" TABLE="auteurs" WHERE="type='auteur'"  WHERE="iddocument='[#ID]'" ORDER="rank" >`
=>
`<LOOP NAME="head_metadonnees_dc_creator" TABLE="auteurs" WHERE="type='auteur'"  WHERE="iddocument='[#ID]'" ORDER="degree" >`

**Comment by brrd** [comment]
Pourriez-vous expliquer quel est le problème svp ? Je ne retrouve rien dans les specs DC qui indique que les métadonnées doivent être présentées dans un ordre plutôt qu'un autre.

**Comment by SylDanh** [comment]
Bonjour,

En effet, mais j'ai remarqué que Google Scholar (https://scholar.google.com/) suivait l'ordre de lecture des métas.

par exemple:  dans la publication [Prairial CJM](https://publications-prairial.fr/cjm/index.php?id=686) l'ordre des auteurs : 

- HTML : James Q. Whitman, Lionel Zevounou et Guillaume Richard
- Source HTML : 
`< meta name="author" content="Richard, Guillaume" />
< meta name="author" content="Zevounou, Lionel" />
< meta name="author" content="Whitman, James Q." />
< meta name="DC.creator" content="Richard, Guillaume" />
< meta name="DC.creator" content="Zevounou, Lionel" />
< meta name="DC.creator" content="Whitman, James Q." />`

- [Google scholar](https://scholar.google.com/scholar?hl=fr&as_sdt=0%2C5&q=Questions+%C3%A0+James+Q.+Whitman+Pr%C3%A9sentation+et+questions+par+Guillaume+Richard+et+Lionel+Zevounou&btnG=) Richard, L Zevounou, JQ Whitman

Hors l'ordre des auteurs est semble t-il fort important pour eux.

**Comment by brrd** [comment]
Merci de votre réponse.
