### ISSUE TITLE
Corriger la distinction entre titre et sous titre dans la table des matières

### ISSUE THREAD

**Issue by oliviercrouzet** [edinum/nova#92]
Ce patch modifie l'affichage des titres d'articles et des titres de parties dans les sommaires de numéros. les seconds étaient en gras et les premiers non, ce qui me paraissait mieux et maintenant c'est l'inverse.
Est-ce que c'est voulu ?
Avant :
![avant](https://user-images.githubusercontent.com/40759024/118521246-206e8700-b73b-11eb-99f7-c39b0cef60d6.png)

Après :
![apres](https://user-images.githubusercontent.com/40759024/118521317-34b28400-b73b-11eb-82db-652a6ba3a265.png)

**Comment by brrd** [comment]
L'idée était surtout de distinguer graphiquement pour chaque article le titre, le sous-titre et la date de publication. Si les titres sont en gras ici, c'est pour les distinguer des sous-titres des articles (qui ne sont pas présents dans votre exemple). On peut envisager de changer ça à partir du moment où cette distinction est respectée, je suis ouvert aux propositions.

À noter qu'il reste possible de surcharger ça dans les CSS du site si besoin.

**Comment by oliviercrouzet** [comment]
Bon, désolé, le truc basique, après la mise à jour, j'ai vidé le cache de Lodel mais pas celui de mon navigateur et ça donnait ce gras sur les titres... Je me voyais déja reprendre le css sur tous nos sites ... Mais par contre en retestant avec le css par défaut je vois que les sous-titres ne se distinguent pas bien des titres (cette fois je ne pense pas que ce soit un problème de cache) . ici le sous-titre _Liens et dissensions.._
![css_orig](https://user-images.githubusercontent.com/40759024/118659599-c084e880-b7ed-11eb-802d-420c176e20b6.png)

**Comment by brrd** [comment]
C'est noté pour une prochaine mise à jour. Merci du retour.
