### ISSUE TITLE
Amélioration: ajout de class dans liste des entrées d'index de personnes

### ISSUE THREAD

**Issue by SylDanh** [edinum/nova#98]
Bonjour,

Dans le fichier [macros_personnes.html](https://github.com/edinum/nova/blob/master/macros_personnes.html), pour uniformiser avec [macros_entrees.html](https://github.com/edinum/nova/blob/master/macros_entrees.html) et avoir un même comportement css, il manque 'class="index-list__list index-list__list--plat' sur le ul.

https://github.com/edinum/nova/blob/ebb1019646d6d2f7283a882e2678ceafd8711954/macros_personnes.html#L104

https://github.com/edinum/nova/blob/ebb1019646d6d2f7283a882e2678ceafd8711954/macros_entrees.html#L99

**Comment by brrd** [comment]
C'est corrigé dans la v2 : https://github.com/edinum/nova/blob/0904988d8942b1ceb110f05acd0cc20fe4334b48/macros_personnes.html#L104
